<?

class Settings
{
    public static $whiteList = array(
                                    # labels
                                    'hospital',
                                    'ram',
                                    'shogun',
                                    'technique',
                                    'metalheadz',
                                    'spearhead',
                                    'owsla',
                                    'playaz',
                                    '3beat',
                                    'fokuz',
                                    'audioporn',
                                    'renegade',
                                    'viper',
                                    'horizons',
                                    'deepsoul',
                                    'liquid',
                                    'kosmos',
                                    'medschool',
                                    'critical',
                                    # artists
                                    'black sun',
                                    'skrillex',
                                    'vortex',
                                    'andyc',
                                    'spectrasoul',
                                    'hamilton',
                                    'spor',
                                    'calibre',
                                    'mefjus',
                                    'fourward',
                                    'tantrum',
                                    'prolix',
                                    'edrush',
                                    's.p.y',
                                    'ulterior',
                                    'hybridminds',
                                    'nelver',
                                    'break',
                                    'sigma',
                                    'technimatic',
                                    'icicle',
                                    'wilkinson',
                                    'friction',
                                    'subfocus',
                                    'fredv',
                                    'tc',
                                    'loadstar',
                                    'prototypes',
                                    'lenzman',
                                    'deltaheavy',
                                    'wickaman',
                                    'lplus',
                                    'joeford',
                                    'insideinfo',
                                    'nu:tone',
                                    'calyx',
                                    'lynx',
                                    'metrik',
                                    'krooked',
                                    'logistics',
                                    'highcontrast',
                                    'reso',
                                    'dcbreaks',
                                    'noisia',
                                    'phace',
                                    'renelavice',
                                    'johnb',
                                    'futurebound',
                                    'trei',
                                    'seba',
                                    'subwave',
                                    'lomax',
                                    'xample',
                                    'chase',
                                    'dannybyrd',
                                    'netsky',
                                    'apex',
                                    'nero',
                                    'brookesbrothers',
                                    'eveson',
                                    'cultureshock'
                                );

    public static $db = array(
                            'uname' => 'adminP8RuGDh',
                            'pass' => 'RXvvKCp8xe4W',
                            'name' => 'dnb',
                            'host' => 'localhost'
                            );
}

?>